# Generated by Django 6.0.2 on 2026-02-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Cetegory',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='images/image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Taxrirlangan sanasi')),
                ('author', models.CharField(max_length=120, verbose_name='muallifi')),
                ('status', models.CharField(choices=[('PB', 'Yaroqli'), ('DF', 'Yaroqsiz')], default='PB', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
