# Generated by Django 6.0.2 on 2026-02-09 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_category_options_news_views_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='Ismi')),
                ('Email', models.EmailField(max_length=254, verbose_name='email')),
                ('massage', models.TextField(verbose_name='xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='islom ochilov', max_length=120, verbose_name='muallifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='project.category'),
        ),
    ]
