# Generated by Django 6.0.2 on 2026-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_boglanish_alter_news_author_alter_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boglanish',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='boglanish',
            old_name='massage',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='boglanish',
            name='Name',
        ),
        migrations.AddField(
            model_name='boglanish',
            name='name',
            field=models.CharField(default=1, max_length=120, verbose_name='Ismi'),
            preserve_default=False,
        ),
    ]
