# Generated by Django 6.0.2 on 2026-02-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_email_boglanish_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boglanish',
            options={'verbose_name': "Bog'lanish", 'verbose_name_plural': "Bog'lanish"},
        ),
    ]
